export const enum LedgerType {
  BILL_CREATED = 'Bill Created',
  BILL_PAID = 'Bill Paid',
  DELETED_BILL = 'BILL DELETED',
  CUSTOMER_REGISTRATION_BILL = 'CUSTOMER REGISTRATION BILL',
  CUSTOMER_REGISTRATION_DELETED = 'CUSTOMER REGISTRATION DELETED',
}
